on: [push]

name: build

jobs:
  build:
    name: Build IDDNS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run cargo build
        run: cargo build --release.yaml --all-features
